name: field_analysis
description: "Field Analysis, yapay zeka kullanarak topraktaki veriyi inceleyip analiz eden ve en uygun tohumları belirleyen yenilikçi bir uygulamadır. İleri veri analiz tekniklerini kullanarak Field Analysis, doğru tohumları toprağın özel koşullarına uygun şekilde eşleştirerek en iyi mahsul verimini ve sağlığını sağlar."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pie_chart: ^5.0.0
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.6
  fl_chart: 0.36.0
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  tflite_flutter: ^0.10.4
  flutter_helper_utils: 1.2.3
  tflite: ^1.1.2
  salomon_bottom_bar: ^3.3.2
  google_maps_flutter: ^2.0.6
  latlong2: ^0.8.1
  flutter_map: ^4.0.0
  shared_preferences: ^2.0.13
  cloud_firestore: ^5.1.0
  logger: ^1.1.0
  image_picker: ^1.1.2
  firebase_storage: 12.1.1
  google_sign_in: ^6.0.1
  flutter_speed_dial: ^5.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: false
  image_path: "assets/pl.png"
  adaptive_icon_background: "#448AFF"
  adaptive_icon_foreground: "assets/1024.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: 0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/ic.png
    - assets/iconx.jpeg
    - assets/corn.svg
    - assets/fertilizer.svg
    - assets/inventory.svg
    - assets/icon2.png
    - assets/simple_random_model.tflite
    - assets/seed_suggestion.tflite
    - assets/seed_suggestion2.tflite
    - assets/seed_suggestion_new.tflite
    - assets/seed_suggestion-2.tflite
    - assets/Untitled_design.png
    - assets/apple.svg
    - assets/barley.svg
    - assets/beans-svgrepo-com.svg
    - assets/blueberries-svgrepo-com.svg
    - assets/carrot-svgrepo-com.svg
    - assets/chili-pepper.svg
    - assets/grapes-svgrepo-com.svg
    - assets/lavender.svg
    - assets/lettuce.svg
    - assets/olive-1-svgrepo-com.svg
    - assets/peach.svg
    - assets/potato.svg
    - assets/tea-cup-mug-svgrepo-com.svg
    - assets/tomato.svg
    - assets/wheat-ear.svg
    - assets/seed-svgrepo-com.svg
    - assets/wheat-svgrepo-com.svg
    - assets/1024.png
    - assets/pl.png